### ISSUE TITLE
Construction/House Timer Not Working

### ISSUE THREAD

**Issue by qldhighway** [Alorel/avabur-improved#3]
![image](https://cloud.githubusercontent.com/assets/15921148/16371076/89498c36-3c87-11e6-9390-d3e0f80bb76d.png)

The housing timer no longer displays the time left until construction is complete.

**Comment by Alorel** [comment]
This will often be caused by lag as it needs to make a request to /house to
obtain it's information. Try opening the house page manually to see if the
timer refreshes (usually takes a couple of seconds) and it it still doesn't
work - refresh the game page.

**Comment by qldhighway** [comment]
Confirmed as not working, tried script in different computer with fresh install.

This ticket should still be open.
