### ISSUE TITLE
House Timers don't work

### ISSUE THREAD

**Issue by Muardin** [Alorel/avabur-improved#4]
Since some weeks the Construction Times always say "Ready", but it isn't.
Maybe the game version changes and so "Avabur Improved" has to change something too.
Hope you find out.

**Comment by Alorel** [comment]
Closing as duplicate of #3.

**Comment by Muardin** [comment]
Oh sorry, didn't saw issue #3 in the list. I try refreshing, if it still don't work i will tell you.
